### ISSUE TITLE
Issues with default parameters

### ISSUE THREAD

**Issue by VeselaHouba** [nixwiz/sensu-go-fatigue-check-filter#20]
https://github.com/nixwiz/sensu-go-fatigue-check-filter/blob/d46f851a32367e50ac4b21d4aac05697737288cb/lib/fatigue_check.js#L1

Hi @nixwiz again :)
I'm not sure why, but the code updated in #18 does not work. 
```
May 10 10:39:24 sensu-go sensu-backend[10256]: {"component":"pipelined","error":"error evaluating /var/cache/sensu/sensu-backend/79142cb649b43e595520c5a1ccb8c365211c83fc1b7509cb3165ef055d51825fe8958b28417eab767cc7f4a3478fe0fe1c5361aff67753a890f8d82ad35d53e9/lib/fatigue_check.js: (anonymous): Line 1:41 Unexpected token = (and 3 more errors)","level":"error","msg":"error executing JS","time":"2020-05-10T10:39:24+02:00"}
```

Following works as expected
```
function fatigue_check(event,occurences,interval) {

    // my defaults
    var occurrences = occurences || 1; // only the first occurrence
    var interval = interval || 1800; // and every 30 minutes thereafter
...
```

I found out that assigning default values in function definition was introduced in ES6, but I don't even know how to check current sensu-go JS version. I'm currently using latest sensu-go version from debian repo
```
root@sensu-go:~# sensu-backend version
sensu-backend version 5.19.3, build 9f7a94a9e4c8fb27abd92721d0949fc265240352, built 2020-05-02T00:27:55Z
```

**Comment by nixwiz** [comment]
Yeah, it appears the Otto JS VM used does not support that.  I'm going to pull the release for now.

**Comment by nixwiz** [comment]
And your example change only works if you *do* pass all three arguments.  And I'm not ready to introduce that breaking change of requiring three.

In the interim, you could fork this repo, put your changes in an add your forked version to Bonsai.

Additionally this surface the fact that my test cases which rely on npm/karma are, at least, partially useless.

**Comment by nixwiz** [comment]
@VeselaHouba i've put in a new release with your code, thanks so much for the help and suggestion!
