### ISSUE TITLE
Allow alerts which do not repeat

### ISSUE THREAD

**Issue by ichilton** [nixwiz/sensu-go-fatigue-check-filter#24]
The filter doesn't seem to allow for alerts which do not repeat.

It would be good to be able to set interval to 0 to get an initial alert and then no repetition.

Currently, that'll get set to 1800 by:

    var interval = interval || 1800; // and every 30 minutes thereafter

Thanks,

Ian

**Comment by nixwiz** [comment]
You should be able to do this by specifying an interval of zero.

`fatigue_check(event, 1, 0)`

Would alert on the first occurrence, but not repeat after.  Except for the resolution, if you are allowing it.

**Comment by nixwiz** [comment]
Turns out that specifying zero as the argument won't work.  The only way to have a zero override as part of an annotation.

I'll be adding this to the README.
