### ISSUE TITLE
Resolution events not suppressed. 

### ISSUE THREAD

**Issue by Capt-Tom** [nixwiz/sensu-go-fatigue-check-filter#26]
I've applied the following type of configuration within every check in my environment. 

```
          "annotations": {
            "fatigue_check/occurrences": "3",
            "fatigue_check/interval": "900",
            "fatigue_check/allow_resolution": "false"
          }
```

Agents have their two fatigue_check options set. 

```
    "annotations": {
      "fatigue_check/keepalive_occurrences": "1",
      "fatigue_check/keepalive_interval": "0",
    }
```

Occurrence configuration is functioning as expected; checks that have issues or alert for fewer than their configured occurrences do not generate warning or critical notifications. 

However, resolution messages are still passing through the pipeline by the hundreds each second. 

```
Description
NTP OK: Offset 0.001697361469 secs|offset=0.001697s;30.000000;60.000000;
Status
Resolved
Entity
host.place-hold-domain.com
```

**Comment by nixwiz** [comment]
Are you sure it's resolution events being passed?  Or simply just passing events?  Are you using the `is_incident` filter along with this filter on your handler(s)?

**Comment by Capt-Tom** [comment]
I believe it's resolution events that are being passed, as the result of the Slack webhook is an event notification with "Resolved" as the status. 

The only filters applied to the handler being used is "not_silenced" and "fatigue_check." I re-ordered them in case that was having any effect.

**Comment by nixwiz** [comment]
The slack handler sets "Resolved" on any event with status == 0 (reference [this function](https://github.com/sensu/sensu-slack-handler/blob/55861a7587f59a7e2ad960703f0ec44699a2be64/main.go#L121) in the handler) Handlers, unlike, filters don't have access to the internal state `is_resolution` which is when an event shifts from non-zero to zero.

If you are not using the `is_incident` filter on the handler the fatigue filter will still pass events based on the occurrence and interval.  It is not doing any other state checking.  I recommend you add the `is_incident` filter to your slack handler.

**Comment by Capt-Tom** [comment]
Thank you for pointing out this oversight. I will make the changes and not the results.

**Comment by Capt-Tom** [comment]
This is absolutely a required filter, thank you kindly for setting my configuration straight. The documentation on this built-in filter can be found in the event reference. https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-filter/filters/
