### ISSUE TITLE
Feature request: Add support for filtering based on entity annotations

### ISSUE THREAD

**Issue by rgeniesse** [nixwiz/sensu-go-fatigue-check-filter#7]
This filter currently only supports filtering based on `check` level annotations. While that is great for normal checks, keepalives do not have annotations inside `event.check.annotations`. As keepalives are always associated with some entity, we can leverage the entity level annotations to filter keepalives based on the same rules that checks have.

**Comment by nixwiz** [comment]
Great idea.  In situations where there could be annotations for both an entity and a check (non-keepalive), which should have precedence.  I would tend to say entity as it would be more granular.  Thoughts?

**Comment by rgeniesse** [comment]
@nixwiz I would agree that entity should win in that situation, as if keepalives aren't working, checks due to the state of the entity (outside of false keepalives due to time being off) usually can't be trusted.

I also believe that in Sensu Classic, client level custom attributes won over check level ones for things like contact routing in Enterprise.
